name: "Publish scripts"

on:
  push:
    branches:
      - master
    paths:
      - scripts/**
      - .github/workflows/scripts.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish scripts to Cloudflare Pages
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy scripts --project-name=tcpbrutalscripts --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}